### ISSUE TITLE
Plugin doesn't work in chrome 54

### ISSUE THREAD

**Issue by RNiveau** [bitcraze/crazyflie-chrome-client#1]
Hi guys,

Your extension doesn't work with chrome 54.0.2840.98 (64-bit) on mac os.

After look at your code, it's seems the permissions in the manifests.json are wrong.
In the authorization windows, no authorization is required.

I change the permissions like this
```
   "permissions":[  
      {  
         "usbDevices":[  
            {  
               "vendorId":6421,
               "productId":30583
            }
         ]
      }
   ],
```

And this appear in the windows:

<img width="457" alt="capture d ecran 2016-12-28 a 20 50 54" src="https://cloud.githubusercontent.com/assets/6623792/21530250/a85be9f4-cd3f-11e6-8c35-5cf0ac87e16b.png">

But, in the application I have this error:

```
crazyradio.js:45 Uncaught TypeError: Cannot read property 'getDevices' of undefined(…)my.open @ crazyradio.js:45document.querySelector.onclick @ main.js:11
```

Is this plugin still alive ?

**Comment by ataffanel** [comment]
This was a proof of concept and I have not been using it very often (my hope was that it would be picked up by someone interested in HTML/JS development). Since Google announced that it will stop supporting chrome app, unfortunately this app might never get finished.

That said I will gladly test and accepts pull-request :-D.

As for the problem, apparently we got out of sync with the USB API. Maybe we are still missing some permission.
